version: '3.3'
services:
  post_db:
<<<<<<< Updated upstream
    image: mongo:${mongo_v}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
=======
    image: mongo:3.2
>>>>>>> Stashed changes
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
<<<<<<< Updated upstream
#    build: ./ui
    image: ${username}/ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${ui_port}:9292/tcp
    networks:
      - back_net
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
#    build: ./post-py
    image: ${username}/post
    networks:
      - front_net
      - back_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post_db
    ports:
      - "5000:5000"

  comment:
#    build: ./comment
    image: ${username}/comment
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - front_net
      - back_net
  prometheus:
    image: ${username}/prometheus
=======

    build: /home/vika/spravcesystemu_microservices/src/ui    
    image: 65435345345/ui
    ports:
      - '9292:9292'
    networks:
      - back_net
  post:
    build: /home/vika/spravcesystemu_microservices/src/post-py
    image: 65435345345/post
    networks:
      - back_net
      - front_net
  comment:
    build: /home/vika/spravcesystemu_microservices/src/comment
    image: 65435345345/comment
    networks:
      - back_net
      - front_net
  prometheus:
    image: 65435345345/prometheus
>>>>>>> Stashed changes
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
<<<<<<< Updated upstream
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - front_net
      - back_net
=======
      - '--storage.tsdb.path=/etc/prometheus/'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - back_net
      - front_net
>>>>>>> Stashed changes
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
<<<<<<< Updated upstream
=======
      - front_net
  mongo-exporter:
    image: percona/mongodb_exporter:0.32.0
    networks:
      - back_net
    command:
      - '--mongodb.uri=mongodb://post_db:27017'
      - '--collect-all'
  blackbox-exporter:
    image: prom/blackbox-exporter:v0.21.0
    user: root
    networks:
      - back_net
      - front_net
>>>>>>> Stashed changes

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
